export const projects = [
  {
    id: "random=1",
    portfolio: "/images/references/p - (1).jpg",
    name:'picsum.photos',
    portfolioSize: {
      w: 300,
      h: 200,
    },
    categories: [],
    projectUrl: "",
    description: "",
  },
  {
    id: "random=2",
    portfolio: "/images/references/p - (2).jpg",
    name:'picsum.photos',
    portfolioSize: {
      w: 300,
      h: 200,
    },
    categories: [],
    projectUrl: "",
    description: "",
  },
  {
    id: "random=3",
    portfolio: "/images/references/p - (3).jpg",
    name:'picsum.photos',
    portfolioSize: {
      w: 300,
      h: 200,
    },
    categories: [],
    projectUrl: "",
    description: "",
  },
  {
    id: "random=4",
    portfolio: "/images/references/p - (4).jpg",
    name:'picsum.photos',
    portfolioSize: {
      w: 300,
      h: 200,
    },
    categories: [],
    projectUrl: "",
    description: "",
  },
  {
    id: "random=5",
    portfolio: "/images/references/p - (5).jpg",
    name: "picsum.photos",
    portfolioSize: {
      w: 300,
      h: 200,
    },
    categories: [],
    projectUrl: "",
    description: "",
  },
  {
    id: "random=6",
    portfolio: "/images/references/p - (6).jpg",
    name: "picsum.photos",
    portfolioSize: {
      w: 300,
      h: 200,
    },
    categories: [],
    projectUrl: "",
    description: "",
  },
  {
    id: "random=7",
    portfolio: "/images/references/p - (7).jpg",
    name:'picsum.photos',
    portfolioSize: {
      w: 300,
      h: 200,
    },
    categories: [],
    projectUrl: "",
    description: "",
  },
  {
    id: "random=8",
    portfolio: "/images/references/p - (8).jpg",
    name:'picsum.photos',
    portfolioSize: {
      w: 300,
      h: 200,
    },
    categories: [],
    projectUrl: "",
    description: "",
  },
];
