export const projects = [
  {
    id: "bilibum.app",
    portfolio: "images/products/bilibum.png",
    name: "Bilibum",
    portfolioSize: {
      w: 300,
      h: 200,
    },
    category: "projects",
    projectUrl: "bilibum.app",
    description: "Merhaba! Size, çocuklarınızın uykusu için en özel ve eğlenceli arkadağı sunmaktan heyecan duyuyoruz. Bilibum olarak, çocuklarınızın rüyalarını renklendiren ve uykularını daha huzurlu hale getiren bir uygulama yaratıyoruz.",
  },
  {
    id: "random=1",
    portfolio: "/images/references/p - (1).jpg",
    name: "Project A",
    portfolioSize: {
      w: 300,
      h: 200,
    },
    category: "e-commerce",
    projectUrl: "",
    description: "Bu projede e-ticaret platformumuzun kullanıcı deneyimini en üst düzeye çıkarmak için çalıştık.",
  },
  {
    id: "random=2",
    portfolio: "/images/references/p - (2).jpg",
    name: "Project B",
    portfolioSize: {
      w: 300,
      h: 200,
    },
    category: "web-site",
    projectUrl: "",
    description: "Bu projede müşterimiz için modern ve etkileyici bir web sitesi tasarladık ve geliştirdik.",
  },
  {
    id: "random=3",
    portfolio: "/images/references/p - (3).jpg",
    name: "Project C",
    portfolioSize: {
      w: 300,
      h: 200,
    },
    category: "production",
    projectUrl: "",
    description: "Bu projede reklam ve medya prodüksiyonu için yaratıcı çözümler sunarak müşterimizin hedef kitlesine ulaşmasını sağladık.",
  },
  {
    id: "random=4",
    portfolio: "/images/references/p - (4).jpg",
    name: "Project D",
    portfolioSize: {
      w: 300,
      h: 200,
    },
    category: "design",
    projectUrl: "",
    description: "Bu projede marka kimliği ve tasarımını yeniden şekillendirerek müşterimizin görsel olarak öne çıkmasını sağladık.",
  },
  {
    id: "random=5",
    portfolio: "/images/references/p - (5).jpg",
    name: "Project E",
    portfolioSize: {
      w: 300,
      h: 200,
    },
    category: "mobile-app",
    projectUrl: "",
    description: "Bu projede kullanıcı dostu bir mobil uygulama tasarlayarak müşterimizin müşteri etkileşimini artırdık.",
  },
  {
    id: "random=6",
    portfolio: "/images/references/p - (6).jpg",
    name: "Project F",
    portfolioSize: {
      w: 300,
      h: 200,
    },
    category: "production",
    projectUrl: "",
    description: "Bu projede bir dizi video içeriği üreterek müşterimizin dijital varlığını güçlendirdik.",
  },
  {
    id: "random=7",
    portfolio: "/images/references/p - (7).jpg",
    name: "Project G",
    portfolioSize: {
      w: 300,
      h: 200,
    },
    category: "digital-marketing",
    projectUrl: "",
    description: "Bu projede dijital pazarlama stratejileri oluşturarak müşterimizin online görünürlüğünü artırdık.",
  },
  {
    id: "random=8",
    portfolio: "/images/references/p - (8).jpg",
    name: "Project H",
    portfolioSize: {
      w: 300,
      h: 200,
    },
    category: "test-automation",
    projectUrl: "",
    description: "Bu projede otomasyon testlerini uygulayarak müşterimizin ürün kalitesini artırdık ve süreçleri optimize ettik.",
  },
];
