export const technologies = [
  {
    id: "Kubernetes",
    title: "Kubernetes",
    category: "Bulut ve Konteyner Yönetimi",
    imageUrl: "/images/technologies/kubernetes.svg",
    isMenuDisplay: true,
    description: `Kubernetes, konteyner tabanlı uygulamaların otomatik dağıtımını ve yönetimini sağlayan güçlü bir yazılım platformudur. Uygulamaların hızlı bir şekilde başlamasını, sorunsuz ölçeklenebilirliği ve kesintisiz hizmet sunmayı mümkün kılar. Deklaratif yapısıyla istenen durumu otomatik olarak gerçekleştirerek geliştiricilere büyük bir operasyonel kolaylık sağlar. Kubernetes, modern uygulama geliştirme süreçlerinde vazgeçilmez bir rol oynar.`,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "Docker",
    title: "Docker",
    category: "Bulut ve Konteyner Yönetimi",
    imageUrl: "/images/technologies/docker.svg",
    isMenuDisplay: true,
    description: `Docker, konteynerleştirme teknolojisi olarak bilinen bir yazılım platformudur. Uygulamaları hafif ve taşınabilir konteynerler halinde paketlemek ve çalıştırmak için kullanılır. Docker, uygulamaların bağımsız olarak çalışmasını sağlar, sistemler arasında tutarlılığı sağlar ve hızlı dağıtım imkanı sunar. Bu sayede uygulama geliştirme ve dağıtım süreçlerinde büyük kolaylık sağlar ve yazılım ekosistemini standartlaştırır.`,
    size: {
      width: 35,
      height: 35,
    },
  },
  {
    id: "NextJs",
    title: "Next.js",
    category: "React Framework",
    imageUrl: "/images/technologies/nextjs.svg",
    isMenuDisplay: true,
    description: "Next.js, modern ve gelişmiş bir React framework'üdür. İleri düzeyde özellikler sunan Next.js ile SSR (Sunucu Taraflı Render), CSR (İstemci Taraflı Render), veri ön yükleme gibi performans artırıcı teknikler kullanabilirsiniz. Yenilikçi yapısıyla React tabanlı projelerinizi hızlandırabilir, SEO dostu uygulamalar geliştirebilirsiniz.",
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "NETCore",
    title: ".NET Core",
    category: "Backend",
    imageUrl: "/images/technologies/dot-net-6.0.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },

  {
    id: "NodeJs",
    title: "NodeJs",
    category: "Backend",
    imageUrl: "/images/technologies/node-js.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 50,
      height: 50,
    },
  },
  {
    id: "MicrosoftSQL",
    title: "Microsoft SQL",
    category: "Veritabanı Yönetimi",
    imageUrl: "/images/technologies/microsoft-sql.svg",
    isMenuDisplay: true,
    description: "Microsoft SQL Server, güçlü veritabanı yönetim sistemlerinden biridir. Veri depolama, işleme ve yönetiminde geniş yetenekler sunar. Büyük ölçekli ve karmaşık veritabanlarını kolayca yönetmenizi sağlar.",
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "Redis",
    title: "Redis",
    category: "Backend",
    imageUrl: "/images/technologies/redis.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "Wordpress",
    title: "Wordpress",
    category: "İçerik Yönetim Sistemi ",
    imageUrl: "/images/technologies/wordpress.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "React.js",
    title: "React.js",
    category: "Frontend",
    imageUrl: "/images/technologies/react-js.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 35,
      height: 35,
    },
  },
  {
    id: "Angular",
    title: "Angular",
    category: "Frontend",
    imageUrl: "/images/technologies/angular.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 35,
      height: 35,
    },
  },
  {
    id: "Figma",
    title: "Figma",
    category: "UX/UI Design",
    imageUrl: "/images/technologies/figma.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 25,
      height: 25,
    },
  },
  {
    id: "GoogleAds",
    title: "Google Ads",
    category: "Dijital Reklam ve Pazarlama",
    imageUrl: "/images/technologies/google-ads.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },

  {
    id: "GoogleMyBusiness",
    title: "Google My Business",
    category: "Dijital Reklam ve Pazarlama",
    imageUrl: "/images/technologies/google-my-business.svg",
    isMenuDisplay: false,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    "id": "GoogleAnalytics",
    "title": "Google Analytics",
    "category": "Web Analitiği",
    "imageUrl": "/images/technologies/google-analytics.svg",
    "isMenuDisplay": true,
    "description": "Google Analytics, web sitenizdeki kullanıcı etkileşimlerini izlemenize ve analiz etmenize yardımcı olan güçlü bir web analitiği hizmetidir. Kullanıcı davranışları, trafik kaynakları ve dönüşüm oranları konusunda değerli içgörüler sunar. Kullanıcı dostu arayüzü ve kapsamlı raporlama araçları ile Google Analytics, çevrimiçi varlığınızı optimize etmek için vazgeçilmez bir araçtır.",
    "size": {
        "width": 32,
        "height": 32
    }
},
  {
    id: "GoogleMerchantCenter",
    title: "Google Merchant Center",
    category: "Dijital Reklam ve Pazarlama",
    imageUrl: "/images/technologies/google-merchant-center.svg",
    isMenuDisplay: false,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },

  {
    id: "GoogleCloud",
    title: "Google Cloud",
    category: "Bulut ve Konteyner Yönetimi",
    imageUrl: "/images/technologies/google-cloud.svg",
    isMenuDisplay: false,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "GoogleDataStudio",
    title: "Google Data Studio",
    category: "Dijital Reklam ve Pazarlama",
    imageUrl: "/images/technologies/google-data-studio.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "MetaBusinessSuite",
    title: "Meta Business Suite",
    category: "Dijital Reklam ve Pazarlama",
    imageUrl: "/images/technologies/meta-business-suite.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "Blender",
    title: "Blender",
    category: "Grafik Tasarım",
    imageUrl: "/images/technologies/blender.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "AdobeIllustrator",
    title: "Adobe Illustrator",
    category: "Grafik Tasarım",
    imageUrl: "/images/technologies/adobe-ai.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "AdobePhotoshop",
    title: "Adobe Photoshop",
    category: "Grafik Tasarım",
    imageUrl: "/images/technologies/adobe-ps.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "AdobePremiere",
    title: "Adobe Premiere Pro",
    category: "Prodüksiyon",
    imageUrl: "/images/technologies/adobe-pr.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "AdobeAfterEffects",
    title: "Adobe After Effects",
    category: "Prodüksiyon",
    imageUrl: "/images/technologies/adobe-ae.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "AdobeXD",
    title: "Adobe XD",
    category: "Prodüksiyon",
    imageUrl: "/images/technologies/adobe-xd.svg",
    isMenuDisplay: false,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "AdobeInDesign",
    title: "Adobe InDesign",
    category: "Grafik Tasarım",
    imageUrl: "/images/technologies/adobe-id.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "UnrealEngine",
    title: "Unreal Engine",
    category: "Oyun Geliştirme",
    imageUrl: "/images/technologies/unreal-engine.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "Unity",
    title: "Unity",
    category: "Oyun Geliştirme",
    imageUrl: "/images/technologies/unity-technologies-logo.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 40,
      height: 40,
    },
  },
  {
    id: "Plesk",
    title: "Plesk",
    category: "Web Hosting ve Yönetim Panelleri",
    imageUrl: "/images/technologies/plesk.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 40,
      height: 40,
    },
  },
  {
    id: "cPanel",
    title: "cPanel",
    category: "Web Hosting ve Yönetim Panelleri",
    imageUrl: "/images/technologies/cPanel.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 40,
      height: 40,
    },
  },
  {
    id: "Selenium",
    title: "Selenium",
    category: "Otomasyon Test Araçları",
    imageUrl: "/images/technologies/selenium.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 40,
      height: 40,
    },
  },
  {
    id: "Appium",
    title: "Appium",
    category: "Otomasyon Test Araçları",
    imageUrl: "/images/technologies/appium.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 60,
      height: 60,
    },
  },
  //
];
