//dahası var

export const technologies = [
  {
    id: "Kubernetes",
    title: "Kubernetes",
    category: "Backend",
    imageUrl: "/images/technologies/kubernetes.svg",
    isMenuDisplay: true,
    description: `Kubernetes, konteyner tabanlı uygulamaların otomatik dağıtımını ve yönetimini sağlayan güçlü bir yazılım platformudur. Uygulamaların hızlı bir şekilde başlamasını, sorunsuz ölçeklenebilirliği ve kesintisiz hizmet sunmayı mümkün kılar. Deklaratif yapısıyla istenen durumu otomatik olarak gerçekleştirerek geliştiricilere büyük bir operasyonel kolaylık sağlar. Kubernetes, modern uygulama geliştirme süreçlerinde vazgeçilmez bir rol oynar.`,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "Docker",
    title: "Docker",
    category: "Backend",
    imageUrl: "/images/technologies/docker.svg",
    isMenuDisplay: true,
    description: `Docker, konteynerleştirme teknolojisi olarak bilinen bir yazılım platformudur. Uygulamaları hafif ve taşınabilir konteynerler halinde paketlemek ve çalıştırmak için kullanılır. Docker, uygulamaların bağımsız olarak çalışmasını sağlar, sistemler arasında tutarlılığı sağlar ve hızlı dağıtım imkanı sunar. Bu sayede uygulama geliştirme ve dağıtım süreçlerinde büyük kolaylık sağlar ve yazılım ekosistemini standartlaştırır.`,
    size: {
      width: 35,
      height: 35,
    },
  },
  {
    id: ".NETCore7.0",
    title: ".NET Core 7.0",
    category: "Backend",
    imageUrl: "/images/technologies/dot-net-6.0.svg",
    isMenuDisplay: true,
    description: `.NET Core 7.0, Microsoft tarafından geliştirilen, açık kaynaklı ve çok platformlu bir yazılım geliştirme çerçevesidir. .NET Core, uygulama geliştiricilerine Windows, macOS ve Linux gibi farklı işletim sistemlerinde çalışabilen yüksek performanslı ve ölçeklenebilir uygulamalar oluşturma imkanı sunar.

    .NET Core 7.0, .NET 7.0 olarak da bilinen son sürümüdür ve yeni ve geliştirilmiş özelliklerle birlikte gelir. Bu sürümde geliştiriciler, geliştirme süreçlerini hızlandıran, uygulama performansını iyileştiren ve daha fazla platform desteği sağlayan bir dizi yenilik bulacaklar.`,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "NodeJs",
    title: "NodeJs",
    category: "Backend",
    imageUrl: "/images/technologies/node-js.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 50,
      height: 50,
    },
  },
  {
    id: "Redis",
    title: "Redis",
    category: "Backend",
    imageUrl: "/images/technologies/redis.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "Wordpress",
    title: "Wordpress",
    category: "İçerik Yönetim Sistemi ",
    imageUrl: "/images/technologies/wordpress.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "React.js",
    title: "React.js",
    category: "Frontend",
    imageUrl: "/images/technologies/react-js.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 35,
      height: 35,
    },
  },
  {
    id: "Angular",
    title: "Angular",
    category: "Frontend",
    imageUrl: "/images/technologies/angular.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 35,
      height: 35,
    },
  },
  {
    id: "Figma",
    title: "Figma",
    category: "UX/UI Design",
    imageUrl: "/images/technologies/figma.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 25,
      height: 25,
    },
  },
  {
    id: "GoogleAds",
    title: "Google Ads",
    category: "İnternet Reklamları",
    imageUrl: "/images/technologies/google-ads.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "GoogleMyBusiness",
    title: "Google My Business",
    category: "Dijital Yerel Pazarlama",
    imageUrl: "/images/technologies/google-my-business.svg",
    isMenuDisplay: false,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "GoogleMerchantCenter",
    title: "Google Merchant Center",
    category: "Dijital Yerel Pazarlama",
    imageUrl: "/images/technologies/google-merchant-center.svg",
    isMenuDisplay: false,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },

  {
    id: "GoogleCloud",
    title: "Google Cloud",
    category: "Backend",
    imageUrl: "/images/technologies/google-cloud.svg",
    isMenuDisplay: false,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "GoogleDataStudio",
    title: "Google Data Studio",
    category: "Dijital Yerel Pazarlama",
    imageUrl: "/images/technologies/google-data-studio.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "MetaBusinessSuite",
    title: "Meta Business Suite",
    category: "Dijital Yerel Pazarlama",
    imageUrl: "/images/technologies/meta-business-suite.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "Blender",
    title: "Blender",
    category: "Grafik Tasarım",
    imageUrl: "/images/technologies/blender.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "AdobeIllustrator",
    title: "Adobe Illustrator",
    category: "Grafik Tasarım",
    imageUrl: "/images/technologies/adobe-ai.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "AdobePhotoshop",
    title: "Adobe Photoshop",
    category: "Grafik Tasarım",
    imageUrl: "/images/technologies/adobe-ps.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "AdobePremiere",
    title: "Adobe Premiere Pro",
    category: "Prodüksiyon",
    imageUrl: "/images/technologies/adobe-pr.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "AdobeAfterEffects",
    title: "Adobe After Effects",
    category: "Prodüksiyon",
    imageUrl: "/images/technologies/adobe-ae.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "AdobeXD",
    title: "Adobe XD",
    category: "Prodüksiyon",
    imageUrl: "/images/technologies/adobe-xd.svg",
    isMenuDisplay: false,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "AdobeInDesign",
    title: "Adobe InDesign",
    category: "Grafik Tasarım",
    imageUrl: "/images/technologies/adobe-id.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "UnrealEngine",
    title: "Unreal Engine",
    category: "Oyun Geliştirme",
    imageUrl: "/images/technologies/unreal-engine.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 32,
      height: 32,
    },
  },
  {
    id: "Unity",
    title: "Unity",
    category: "Oyun Geliştirme",
    imageUrl: "/images/technologies/unity-technologies-logo.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 40,
      height: 40,
    },
  },
  {
    id: "Plesk",
    title: "Plesk",
    category: "",
    imageUrl: "/images/technologies/plesk.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 40,
      height: 40,
    },
  },
  {
    id: "cPanel",
    title: "cPanel",
    category: "",
    imageUrl: "/images/technologies/cPanel.svg",
    isMenuDisplay: true,
    description: ``,
    size: {
      width: 40,
      height: 40,
    },
  },
  
  //
];
