export const technologies = [
  {
    id: "Kubernates",
    title: "Kubernates",
    category: "Backend",
    imageUrl: "images/technologies/kubernates.svg",
  },
  {
    id: ".NET Core 6.0",
    title: ".NET Core 6.0",
    category: "Backend",
    imageUrl: "images/technologies/dot-net-6.0.svg",
  },
  {
    id: "Redis",
    title: "Redis",
    category: "Backend",
    imageUrl: "images/technologies/redis.svg",
  },
  {
    id: "React.js",
    title: "React.js",
    category: "Frontend",
    imageUrl: "images/technologies/react-js.svg",
  },
  {
    id: "React Native",
    title: "React Native",
    category: "Frontend",
    imageUrl: "images/technologies/react-native.svg",
  },
  {
    id: "Figma",
    title: "Figma",
    category: "UX/UI Design",
    imageUrl: "images/technologies/figma.svg",
  },
  {
    id: "Google Ads",
    title: "Google Ads",
    category: "İnternet Reklamları",
    imageUrl: "images/technologies/google-ads.svg",
  },
  {
    id: "Google My Business",
    title: "Google My Business",
    category: "Dijital Yerel Pazarlama",
    imageUrl: "images/technologies/google-my-business.svg",
  },
  {
    id: "Adobe Photoshop",
    title: "Adobe Photoshop",
    category: "Grafik Tasarım",
    imageUrl: "images/technologies/adobe-ps.svg",
  },
  {
    id: "Blender",
    title: "Blender",
    category: "Grafik Tasarım",
    imageUrl: "images/technologies/blender.svg",
  },
  {
    id: "Adobe Illustrator",
    title: "Adobe Illustrator",
    category: "Grafik Tasarım",
    imageUrl: "images/technologies/adobe-ai.svg",
  },
  {
    id: "Adobe After Effects",
    title: "Adobe After Effects",
    category: "Prodüksiyon",
    imageUrl: "images/technologies/adobe-ae.svg",
  },
  {
    id: "Docker",
    title: "Docker",
    category: "Backend",
    imageUrl: "images/technologies/docker.svg",
  },
];
