# Use an official Nginx image as the base image
FROM nginx

# Copy your custom Nginx configuration to the container
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Remove the default Nginx welcome page
RUN rm /etc/nginx/conf.d/default.conf

# Expose the port Nginx will run on (usually port 80)
EXPOSE 80
